/****** Object:  Table [dbo].[CardStatuses]    Script Date: 24.07.2019 13:16:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CardStatuses](
	[IDCardStatus] [int] IDENTITY(1,1) NOT NULL,
	[Code] [text] NOT NULL,
	[Name] [text] NOT NULL,
 CONSTRAINT [PK_CardStatuses] PRIMARY KEY CLUSTERED 
(
	[IDCardStatus] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


